server:
   port: 9000

spring:
   application:
      name: "cards"
   profiles:
      active: "default"
   datasource:
      url: "jdbc:h2:mem:testdb"
      driverClassName: org.h2.Driver
      username: sa
      password: ''
   h2:
    console.enabled: true
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
   config:
      import: "optional:configserver:http://localhost:8071/"

   rabbitmq:
      host: "localhost"
      port: 5672
      username: "guest"
      password: "guest"
      
management:
   endpoints:
      web:
         exposure:
            include: "*"    
   info:
     env:
        enabled: true
        
eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://localhost:8070/eureka 

info:
   app:
      name: ${spring.application.name}
      description: "Microservizio che gestisce le cards"
      version: "1.0.0"
              
version: 0.0.1
