services:
   network-service:
      networks:
         - eustema 
         
   base-service:
      extends:
         service: network-service
      environment:
         SPRING_RABBITMQ_HOST: "rabbit"
         
   application-service:
      extends:
         service: base-service
      depends_on:
         eurekaserver:
            condition: service_healthy
      environment:
         SPRING_CONFIG_IMPORT: "optional:configserver:http://configurationserver:8071/"
         SPRING_PROFILES_ACTIVE: "default"
         SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
         SPRING_DATASOURCE_USERNAME: root
         SPRING_DATASOURCE_PASSWORD: pippo
         EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
   
   microservice-db:
      extends:
         service: network-service
      image: mysql:8.4.2
      healthcheck:
         test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
         timeout: 10s
         retries: 10
         interval: 10s
         start_period: 10s
      environment:
         MYSQL_ROOT_PASSWORD: pippo