networks:
   eustema:
      driver: "bridge"
      
services:
   configserver:
      networks:
         - eustema  
      container_name: "eustema_configserver"
      image: "eustema_configserver:v1"
      build:
         context: "../../configserver"
      ports:
         - 8071:8071
      healthcheck:
         test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
         interval: 10s
         timeout: 5s
         retries: 10
         start_period: 10s
   accounts:
      networks:
         - eustema
      container_name: "eustema_accounts"
      image: "eustema_accounts:v1"
      build:
         context: "../../accounts"
      ports:
         - 8080:8080
      depends_on:
         configserver:
            condition: service_healthy
      environment:
         SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071/"
      